version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: clrt_local
      MYSQL_USER: clrt_user
      MYSQL_PASSWORD: clrt_pwd
      MYSQL_ROOT_PASSWORD: clrt_root_pwd
      MYSQL_PORT: 3306
    ports:
      - "4306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: clrt_mysql_host

  web:
    build: .
    command: bash -c "./start.sh"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    container_name: clrt_web

volumes:
  mysql-data: